module ObjectStateMsg {

    // Trạng thái của 1 object: vị trí, vận tốc, heading, status
    @final
    struct ObjectState {
        unsigned long long frame_id;    // id frame đảm bảo cùng 1 frame khi xử lý
        long long timestamp_ns; // epoch nanoseconds của frame
        @key long object_id;   
        float pos_x;
        float pos_y;
        float pos_z;
        float vel_x;
        float vel_y;
        float vel_z;
        float heading;     // radian
        octet status;      // 0=inactive, 1=active, 2=lost
    };

};
